apiVersion: apps/v1
kind: Deployment
metadata:
  name: pawfect-match-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pawfect-match
  template:
    metadata:
      labels:
        app: pawfect-match
    spec:
      containers:
      - name: pawfect-match-container
        image: pawfect-match:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pawfect-match-service
spec:
  type: NodePort
  selector:
    app: pawfect-match
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
