apiVersion: v1
kind: Service
metadata:
  name: pawfect-match-service
spec:
  type: NodePort  # Change to LoadBalancer if using cloud provider
  selector:
    app: pawfect-match
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000  # Port exposed on cluster nodes
